# Generated by Django 4.1.3 on 2024-04-02 03:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0079_alter_wire_dateacquired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wire",
            name="winch",
        ),
        migrations.AlterField(
            model_name="wire",
            name="dateacquired",
            field=models.DateField(
                blank=True,
                db_column="DateAcquired",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
                verbose_name="Date Acquired",
            ),
        ),
    ]
