# Generated by Django 4.1.3 on 2024-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0082_alter_factorofsafety_options_alter_breaktest_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="wirerinse",
            field=models.BooleanField(
                blank=True, db_column="Wirerinse", null=True, verbose_name="Wire rinse"
            ),
        ),
    ]
