# Generated by Django 4.1.3 on 2024-07-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0083_cast_wirerinse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wire",
            name="status",
            field=models.BooleanField(
                blank=True, db_column="Status", null=True, verbose_name="Active status"
            ),
        ),
    ]
