# Generated by Django 4.1.3 on 2024-07-16 02:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0084_alter_wire_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wire",
            name="dateacquired",
            field=models.DateField(
                blank=True,
                db_column="DateAcquired",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
                verbose_name="Date acquired",
            ),
        ),
        migrations.AlterField(
            model_name="wire",
            name="wirerope",
            field=models.ForeignKey(
                blank=True,
                db_column="WireRopeId",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wwdb.wireropedata",
                verbose_name="Wire type",
            ),
        ),
    ]
