# Generated by Django 4.1.3 on 2024-07-26 04:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0086_cast_factorofsafety_cast_safeworkingtension_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cast",
            name="startdate",
            field=models.DateTimeField(
                blank=True,
                db_column="StartDate",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime.today
                    )
                ],
                verbose_name="Start date and time",
            ),
        ),
    ]
