# Generated by Django 4.1.3 on 2024-07-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wwdb", "0087_alter_cast_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="duration",
            field=models.IntegerField(
                blank=True, db_column="Duration", null=True, verbose_name="Duration"
            ),
        ),
    ]
